let state={data:null,settings:null,week:0};
const $=s=>document.querySelector(s);
const pace=(m,d)=>d?`${Math.floor((m/d)*60)}:${String(Math.round(((m/d)*60%1)*60)).padStart(2,'0')}/km`:'–';
const km=m=>(m/1000).toFixed(1);
function sessionSport(s){return (s.sport?.id||s.sport?.name||'').toString().toLowerCase()}
function isRun(s){return sessionSport(s).includes('run')||sessionSport(s).includes('laufen')||!s.sport}
function actualPace(s){return pace((s.durationMillis||0)/3600000,s.distanceMeters/1000)}
function weekSessions(w){return state.data.sessions.filter(s=>{const d=String(s.startTime).slice(0,10);return d>=w.start&&d<=w.end&&isRun(s)}).sort((a,b)=>a.startTime.localeCompare(b.startTime))}
function match(wi,planned){const runs=weekSessions(state.data.plan[wi]); if(!runs.length)return null;const p=new Date(planned.date+'T12:00:00Z').getTime();return runs.map(s=>({s,score:Math.abs(new Date(s.startTime).getTime()-p)})).sort((a,b)=>a.score-b.score)[0]?.s||null}
function adaptive(wi){const w=state.data.plan[wi], runs=weekSessions(w); if(!runs.length)return {title:'Noch keine Polar-Daten',text:'Sobald ein Lauf synchronisiert ist, wird die Woche automatisch bewertet.'}; const total=runs.reduce((a,s)=>a+(s.distanceMeters||0),0)/1000;const load=runs.reduce((a,s)=>a+(s.trainingLoad||0),0);const easy=runs.filter(s=>s.hrAvg&&s.distanceMeters).map(s=>s.hrAvg).filter(Boolean);const avg=easy.length?Math.round(easy.reduce((a,b)=>a+b,0)/easy.length):null; if(load>700)return {title:'Belastung hoch',text:`Diese Woche liegen ca. ${Math.round(load)} Polar Training Load an. Nächste harte Einheit um 20–30 % kürzen und den langen Lauf locker halten.`}; if(avg&&avg>158)return {title:'Herzfrequenz erhöht',text:`Durchschnittliche HF der Läufe: ${avg} bpm. Wenn die Pace dabei nicht besser wird, Intensität reduzieren und Erholung priorisieren.`}; return {title:'Plan wie vorgesehen',text:`${total.toFixed(1)} km erfasst. Die nächste Woche kann regulär fortgesetzt werden; fehlende Einheiten nicht nachholen.`}}
function render(){const p=state.data.plan;$('#week').innerHTML=p.map((w,i)=>`<option value="${i}">KW ${w.week} · ${w.start}–${w.end}</option>`).join('');$('#week').value=state.week;const w=p[state.week];$('#weekInfo').innerHTML=`<div class="weekmeta"><span class="tag">${w.phase}</span><span class="tag">${w.start} bis ${w.end}</span><span class="tag">3 Läufe/Woche</span></div>`;$('#sessions').innerHTML=w.sessions.map(x=>{const a=match(state.week,x);return `<div class="workout"><div><div class="date">${x.day}</div><div class="type">${x.date}</div></div><div><strong>${x.title}</strong><div class="detail">${x.detail}</div>${a?`<div class="muted">Polar: ${km(a.distanceMeters)} km · ${actualPace(a)} · Ø HF ${a.hrAvg||'–'} · Load ${a.trainingLoad||'–'}</div>`:''}</div><div class="${a?'match':'match warn'}">${a?'erfasst':'offen'}</div></div>`}).join('');const runs=weekSessions(w);$('#runs').innerHTML=runs.length?runs.map(s=>`<div class="run"><div class="runmain"><strong>${String(s.startTime).slice(0,10)}</strong><strong>${km(s.distanceMeters)} km</strong></div><div class="muted">${actualPace(s)} · Ø HF ${s.hrAvg||'–'} · Load ${s.trainingLoad||'–'} · ${s.trainingBenefit||''}</div></div>`).join(''):'<div class="muted">Keine Läufe für diese Woche synchronisiert.</div>';const ad=adaptive(state.week);$('#advice').innerHTML=`<div class="advice"><strong>${ad.title}</strong><br>${ad.text}</div>`;const all=state.data.sessions.filter(isRun);const today=new Date();const upcoming=w.sessions.find(x=>new Date(x.date+'T23:59:59')>=today)||w.sessions[0];$('#next').textContent=upcoming.title;$('#nextDetail').textContent=upcoming.date+' · '+upcoming.detail;const thisWeek=weekSessions(w).reduce((a,s)=>a+(s.distanceMeters||0),0)/1000;$('#km').textContent=thisWeek.toFixed(1)+' km';$('#kmDetail').textContent=`von ca. ${w.sessions.reduce((a,s)=>a+(s.title==='Langer Lauf'?Number((s.detail.match(/\d+/)||[0])[0]):10),0)} km geplant`;$('#syncTime').textContent=state.data.syncedAt?new Date(state.data.syncedAt).toLocaleString('de-CH',{dateStyle:'short',timeStyle:'short'}):'noch nie';$('#sessionCount').textContent=all.length+' Läufe gespeichert';const load=weekSessions(w).reduce((a,s)=>a+(s.trainingLoad||0),0);$('#load').textContent=load?Math.round(load):'–';$('#loadText').textContent=load>700?'hoch':load?'normal':'keine Daten';$('#maxHr').value=state.settings.maxHr;$('#restHr').value=state.settings.restHr;$('#goalPace').value=state.settings.goalPace}
async function load(){const [data,settings,config]=await Promise.all([fetch('/api/data').then(r=>r.json()),fetch('/api/settings').then(r=>r.json()),fetch('/api/config').then(r=>r.json())]);state.data=data;state.settings=settings;$('#status').textContent=config.connected?'Polar verbunden':'Polar nicht verbunden';$('#connect').style.display=config.connected?'none':'inline-block';if(config.connected){$('#sync').style.display='inline-block'}else{$('#sync').style.display='none'}render()}
$('#week').addEventListener('change',e=>{state.week=Number(e.target.value);render()});$('#sync').addEventListener('click',async()=>{const b=$('#sync');b.disabled=true;b.textContent='Synchronisiere…';const r=await fetch('/api/sync',{method:'POST'});if(!r.ok)alert((await r.json()).error);await load();b.disabled=false;b.textContent='Jetzt synchronisieren'});$('#save').addEventListener('click',async()=>{await fetch('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({maxHr:Number($('#maxHr').value),restHr:Number($('#restHr').value),goalPace:Number($('#goalPace').value)})});alert('Gespeichert');});load();
